/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-04-25 23:04:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import data.Yapes;
import data.Logins;

public final class adminDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("data.Yapes");
    _jspx_imports_classes.add("data.Logins");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	List<Yapes> yapeList = (List<Yapes>) request.getAttribute("ListaYapes");
	List<Logins> userList = (List<Logins>) request.getAttribute("ListaUsuarios");

      out.write("\r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <html>\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta charset=\"ISO-8859-1\">\r\n");
      out.write("            <title>Admin Dashboard</title>\r\n");
      out.write("            <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("            <style>\r\n");
      out.write("                .container {\r\n");
      out.write("                    margin: 65px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                .buscarContainer{\r\n");
      out.write("                	display: flex;\r\n");
      out.write("                	gap: 12px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                form {\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    gap: 20px;\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                #buscar{\r\n");
      out.write("                	margin-left: auto;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                input:hover {\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                }\r\n");
      out.write("            </style>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h1>Bienvenido</h1>\r\n");
      out.write("                <br>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <form action=\"Servlet\" method=\"post\">\r\n");
      out.write("                        <input type=\"submit\" value=\"Mostrar Yapes\" name=\"type\">\r\n");
      out.write("						<input type=\"submit\" value=\"Mostrar Usuarios\" name=\"type\">\r\n");
      out.write("                        <div class=\"buscarContainer\">\r\n");
      out.write("                        	<input type=\"text\" name=\"txtBuscar\"\r\n");
      out.write("                        	");
 
                        		String IDStatus = "Ingresa el ID del Yape";
                        		if(request.getAttribute("IDInvalido") != null) { 
                        			IDStatus = (String) request.getAttribute("IDInvalido");
                        		}
                        	
      out.write("\r\n");
      out.write("                        	placeholder=\"");
      out.print( IDStatus );
      out.write("\">\r\n");
      out.write("                        	<input type=\"submit\" value=\"Buscar Yape\" name=\"type\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input id=\"buscar\" type=\"submit\" value=\"Cerrar Sesion\" name=\"type\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <br>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Tabla de Yapes -->\r\n");
      out.write("                \r\n");
      out.write("                ");

                	if(yapeList != null){
                
      out.write("\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>IdYape</th>\r\n");
      out.write("                            <th>Numero que lo realiza</th>\r\n");
      out.write("                            <th>Numero que lo recibe</th>\r\n");
      out.write("                            <th>Monto</th>\r\n");
      out.write("                            <th>Fecha</th>\r\n");
      out.write("                            <th>Hora</th>\r\n");
      out.write("                            <th>Estado</th>\r\n");
      out.write("                            <th>Acciones</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                   			");

								for(Yapes item : yapeList){
							
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td id=\"idYapeLista\">");
      out.print( item.getIdYape() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getNumeroRealizante() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getNumeroRecibiente() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getMonto() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getFecha() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getHora() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getEstado() );
      out.write("</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<a href=\"Servlet?type=Buscar Yape&id=");
      out.print(item.getIdYape());
      out.write("\">Mas info</a>\r\n");
      out.write("								<a href=\"Servlet?type=Buscar Yape a Editar&id=");
      out.print(item.getIdYape());
      out.write("\">Editar</a>\r\n");
      out.write("								<a href=\"Servlet?type=Eliminar Yape&id=");
      out.print(item.getIdYape());
      out.write("&numeroRec=");
      out.print(item.getNumeroRecibiente());
      out.write("&numeroRem=");
      out.print(item.getNumeroRealizante());
      out.write("&monto=");
      out.print(item.getMonto());
      out.write("\">Eliminar</a>				\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <!-- Tabla de Usuarios -->\r\n");
      out.write("                \r\n");
      out.write("                ");

                	if(userList != null){
                
      out.write("\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>IdUsuario</th>\r\n");
      out.write("                            <th>Tipo de Usuario</th>\r\n");
      out.write("                            <th>Nombres Y Apellidos</th>\r\n");
      out.write("                            <th>Saldo</th>\r\n");
      out.write("                            <th>Numero</th>\r\n");
      out.write("                            <th>Clave</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                   			");

								for(Logins item : userList){
							
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td id=\"idYapeLista\">");
      out.print( item.getIdUsuario() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getTipoUsuario() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getNombreApellidos() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getSaldo() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( item.getNumero() );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
