/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-05-04 16:14:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import data.Yapes;
import data.Logins;
import gestion.Metodos;

public final class clientDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("gestion.Metodos");
    _jspx_imports_classes.add("data.Yapes");
    _jspx_imports_classes.add("data.Logins");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

double dinero = 0.0;
Metodos metodo = new Metodos();
if (request.getAttribute("saldo") != null) {
	Logins saldo = (Logins) request.getAttribute("saldo");
	dinero = saldo.getSaldo();
}

List<Yapes> yapeList = (List<Yapes>) request.getAttribute("ListaYapes");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link href=\"Resources/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Client Dashboard</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: purple;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	padding: 50px;\r\n");
      out.write("	margin-top: 100px;\r\n");
      out.write("	margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#servlet-btn {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buscarContainer {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 8px;\r\n");
      out.write("	margin-right: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#asu {\r\n");
      out.write("	gap: 8px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	height: max-content;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ref{\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form div {\r\n");
      out.write("	justify-self: start;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<main class=\"border rounded\">\r\n");
      out.write("			<section id=\"servlet-btn\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					Hola\r\n");
      out.write("					");
      out.print(metodo.obtenerNombre());
      out.write("</h1>\r\n");
      out.write("				<h3>\r\n");
      out.write("					Saldo :\r\n");
      out.write("					");

				if (dinero == 0.0) {
				
      out.write("OCULTO");

				} else {
				
      out.write("\r\n");
      out.write("					");
      out.print(dinero);
      out.write("\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("				</h3>\r\n");
      out.write("				<br>\r\n");
      out.write("				<div>\r\n");
      out.write("					<form action=\"Servlet\" method=\"post\">\r\n");
      out.write("						<div id=\"asu\" class=\"container\">\r\n");
      out.write("							<input class=\"btn btn-primary\" type=\"submit\" value=\"Nuevo Yapeo\"\r\n");
      out.write("								name=\"type\"> <input class=\"btn btn-primary\"\r\n");
      out.write("								type=\"submit\" value=\"Consultar Saldo\" name=\"type\"> <input\r\n");
      out.write("								class=\"btn btn-primary\" type=\"submit\" value=\"Historial de Yapes\"\r\n");
      out.write("								name=\"type\">\r\n");
      out.write("							<div class=\"buscarContainer\">\r\n");
      out.write("								<input class=\"btn btn-primary\" type=\"submit\" value=\"Buscar Yape\"\r\n");
      out.write("									name=\"type\"> <input class=\"form form-control\" size=\"8\"\r\n");
      out.write("									type=\"text\" name=\"txtBuscar\"\r\n");
      out.write("									");
String IDStatus = "Ingresa el ID";
if (request.getAttribute("IDInvalido") != null) {
	IDStatus = (String) request.getAttribute("IDInvalido");
}
      out.write("\r\n");
      out.write("									placeholder=\"");
      out.print(IDStatus);
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<input class=\"btn btn-primary\" id=\"cerrar\" type=\"submit\"\r\n");
      out.write("								value=\"Cerrar Sesion\" name=\"type\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			<section>\r\n");
      out.write("				<table class=\"table table-hover table-striped border rounded\">\r\n");
      out.write("					<thead class=\"table-primary\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>IdYape</th>\r\n");
      out.write("							<th>Numero que lo realiza</th>\r\n");
      out.write("							<th>Numero que lo recibe</th>\r\n");
      out.write("							<th>Monto</th>\r\n");
      out.write("							<th>Fecha</th>\r\n");
      out.write("							<th>Hora</th>\r\n");
      out.write("							<th>Acciones</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

						if (yapeList != null) {
							for (Yapes item : yapeList) {
						
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td id=\"idYapeLista\">");
      out.print(item.getIdYape());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getNumeroRealizante());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getNumeroRecibiente());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getMonto());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getFecha());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getHora());
      out.write("</td>\r\n");
      out.write("							<td class=\"ref\">\r\n");
      out.write("								<a title=\"Info\" href=\"Servlet?type=Buscar Yape&id=");
      out.print(item.getIdYape());
      out.write("\">\r\n");
      out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-info-square-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("										<path d=\"M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm8.93 4.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM8 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2\" />\r\n");
      out.write("									</svg></a>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

						}
						}
						
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</section>\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
