/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2024-05-04 15:36:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import gestion.Metodos;
import java.util.List;
import data.Yapes;
import data.Logins;

public final class headAdminDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("gestion.Metodos");
    _jspx_imports_classes.add("data.Yapes");
    _jspx_imports_classes.add("data.Logins");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

List<Logins> userList = (List<Logins>) request.getAttribute("ListaUsuarios");
Metodos metodo = new Metodos();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>HeadAdmin Dashboard</title>\r\n");
      out.write("<link href=\"Resources/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("	background-color: purple;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main{\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	margin-top: 80px;\r\n");
      out.write("	margin-bottom: 65px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#btn-group{\r\n");
      out.write("	padding: 45px 60px 0px 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table-group{\r\n");
      out.write("	padding: 0px 80px 30px 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buscarContainer {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	margin: 25px 120px auto 120px;\r\n");
      out.write("	gap: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#buscar {\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<main class=\"border rounded\">\r\n");
      out.write("			<section id=\"btn-group\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<h1>Hola, ");
      out.print( metodo.obtenerNombre() );
      out.write("</h1>\r\n");
      out.write("					<form action=\"Servlet\" method=\"post\">\r\n");
      out.write("						<input class=\"btn btn-primary\" type=\"submit\" value=\"Nuevo Usuario\" name=\"type\"> \r\n");
      out.write("						<input class=\"btn btn-primary\" type=\"submit\" value=\"Mostrar Usuarios\" name=\"type\"> \r\n");
      out.write("						<input class=\"btn btn-secondary\" id=\"buscar\" type=\"submit\" value=\"Cerrar Sesion\" name=\"type\">\r\n");
      out.write("					</form>\r\n");
      out.write("					<br>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("			<section id=\"table-group\">\r\n");
      out.write("				<table class=\"table table-hover table-striped border rounded\">\r\n");
      out.write("					<thead class=\"table-primary\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>IdUsuario</th>\r\n");
      out.write("							<th>Tipo de Usuario</th>\r\n");
      out.write("							<th>Nombres Y Apellidos</th>\r\n");
      out.write("							<th>Saldo</th>\r\n");
      out.write("							<th>Numero</th>\r\n");
      out.write("							<th>Clave</th>\r\n");
      out.write("							<th>Acciones</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

						if (userList != null) {
							for (Logins item : userList) {
						
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print(item.getIdUsuario());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getTipoUsuario());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getNombreApellidos());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getSaldo());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getNumero());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(item.getClave());
      out.write("</td>\r\n");
      out.write("							<td>\r\n");
      out.write("								<a title=\"Editar\" href=\"Servlet?type=Buscar Usuario a Editar&id=");
      out.print(item.getIdUsuario());
      out.write("\">\r\n");
      out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-file-earmark-medical-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("  										<path d=\"M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1m-3 2v.634l.549-.317a.5.5 0 1 1 .5.866L7 7l.549.317a.5.5 0 1 1-.5.866L6.5 7.866V8.5a.5.5 0 0 1-1 0v-.634l-.549.317a.5.5 0 1 1-.5-.866L5 7l-.549-.317a.5.5 0 0 1 .5-.866l.549.317V5.5a.5.5 0 1 1 1 0m-2 4.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1m0 2h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1\" />\r\n");
      out.write("  									</svg></a>\r\n");
      out.write("  									\r\n");
      out.write("								<a title=\"Eliminar\" href=\"Servlet?type=Eliminar Usuario&id=");
      out.print(item.getIdUsuario());
      out.write("\">\r\n");
      out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"red\" class=\"bi bi-x-square-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("  										<path d=\"M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708\" />\r\n");
      out.write("									</svg></a>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						");

						}
						}
						
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("			</section>\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
