-- THIS SCRIPT ASUMES THAT THE DB 'BDYAPE' HAS BEEN CREATED, IS UP AND RUNNING WITH CREATED BUT EMPTY TABLES

USE DBYAPE;

/*
	MODELO PARA INSERTAR NUEVO USUARIO
    (HEADADMIN, ADMIN, CLIENTE)
*/
-- ------------------------------- DEMO -----------------------------
-- USUARIO.CLIENTE 1
-- PASO 1: INSERTAR DATOS EN LA TABLA MODELO DE USUARIOS
	INSERT INTO LOGINS.USUARIO
		(DNI_USU, TIP_USU, NOM_USU, APE_USU, TEL_USU, CON_USU)
	VALUES
		('72898111', 'Cliente', 'Diego Anderson', 'Villena Arias', '931888777', 'DIEGO123');
-- PASO 2: SI ES CLIENTE, INGRESAR SALDO, SI ES OTRO TIPO DE USUARIO AGREGAR LOS DATOS ACORDES
	INSERT INTO LOGINS.USUARIO_CLIENTE 
    (COD_CLI, SAL_CLI)
	VALUES
		(1, 200.50);
        
-- USUARIO.CLIENTE 2
	INSERT INTO LOGINS.USUARIO
		(DNI_USU, TIP_USU, NOM_USU, APE_USU, TEL_USU, CON_USU)
	VALUES
		('72898222', 'Cliente', 'Joseph Manuel', 'Villena Arias', '912888777', 'JOSEPH123');
        
	INSERT INTO LOGINS.USUARIO_CLIENTE
    (COD_CLI, SAL_CLI)
	VALUES
		(2, 200.50);
        
-- USUARIO.CLIENTE 3
	INSERT INTO LOGINS.USUARIO
		(DNI_USU, TIP_USU, NOM_USU, APE_USU, TEL_USU, CON_USU)
	VALUES 
		('98329012', 'Cliente', 'Laura Camila', 'Sanchez Ruiz', '945888777', 'LAURA123');

	INSERT INTO LOGINS.USUARIO_CLIENTE
    (COD_CLI, SAL_CLI)
	VALUES 
		(3, 120.62);
-- PASO 3: COMPROBAR LOS DATOS INGRESADOS
	/* 
		SELECT * 
		FROM LOGINS.USUARIO AS U
			INNER JOIN LOGINS.USUARIO_CLIENTE AS C
			ON U.COD_USU = C.COD_CLI
		WHERE C.COD_CLI = 1 AND U.COD_USU = 1; 		-- ELIMNAR EL WHERE PARA LISTAR TODOS LOS USUARIOS
    */
    
    -- BONUS 
    
    -- INSERTAR ADMIN
    INSERT INTO LOGINS.USUARIO
		(DNI_USU, TIP_USU, NOM_USU, APE_USU, TEL_USU, CON_USU)
	VALUES 
		('38472921', 'Admin', 'Luis Daniel', 'Medrano Peña', '938575123', 'Luis883');

	INSERT INTO LOGINS.USUARIO_ADMIN
    (COD_ADM)
	VALUES 
		(4);
    
    -- INSERTAR HEADADMIN
	INSERT INTO LOGINS.USUARIO
		(DNI_USU, TIP_USU, NOM_USU, APE_USU, TEL_USU, CON_USU)
	VALUES 
		('89370244', 'HeadAdmin', 'Manuel James', 'Campos Cruz', '937857121', 'mANuel94');

	INSERT INTO LOGINS.USUARIO_HEADADMIN
    (COD_HEA, SUE_HEA)
	VALUES 
		(5, 3820.32);

/*
	MODELO PARA REALIZAR UNA TRANSACCION (YAPE)
*/

-- PASO 1: INSERTAR EN LA TABLA YAPE LOS DATOS DEL NUMERO RECIBIENTE, NUMERO REALIZANTE Y MONTO (ASEGURAR QUE TODOS LOS DATOS SEAN VALIDOS)
	INSERT INTO TRANSACCIONES.YAPE
		(NRC_YAP, NRT_YAP, MON_YAP)
	VALUES
		('931888777','912888777','10.5');
-- PASO 2 : ASOCIAR LA TRANSACCION CON EL NUMERO REALIZANTE/RECIBIENTE
	INSERT INTO TRANSACCIONES.DETALLE_USUYAPE
	VALUES (1,1);	-- USUARIO 1 CON YAPE 1

	INSERT INTO TRANSACCIONES.DETALLE_USUYAPE
	VALUES (2,1);	-- USUARIO 2 CON YAPE 1

-- PASO 3: COMPROBAR LA TRANSACCION
	/* 
    DISCLAIMER : LISTA CASI TODOS LOS DATOS DEL USUARIO, AGREGAR O ELIMINAR DATOS SEGUN NECESIDAD
    
	SELECT 	U.COD_USU, U.DNI_USU, U.TIP_USU, U.NOM_USU, U.APE_USU, U.TEL_USU, U.FCC_USU,
			Y.COD_YAP, Y.NRC_YAP, Y.NRT_YAP, Y.MON_YAP, Y.FEC_YAP, Y.EST_YAP
	FROM LOGINS.USUARIO 							AS U 
		INNER JOIN TRANSACCIONES.DETALLE_USUYAPE 	AS DT
			ON U.COD_USU = DT.COD_USU
		INNER JOIN TRANSACCIONES.YAPE 				AS Y
			ON DT.COD_YAP = Y.COD_YAP
	WHERE Y.COD_YAP = 1;
    */

/*
	MODELO PARA MODIFICAR UNA TRANSACCION (YAPE)
*/

-- PASO 1 : ACTUALIZAR LA TABLA YAPES
		UPDATE TRANSACCIONES.YAPE
			SET NRC_YAP = 945888777,
				MON_YAP = 30.00, 
				FEC_YAP= NOW(), 
                EST_YAP='Modificado'
		WHERE COD_YAP = 1;
-- PASO 2 : ACTUALIZAR LA TABLA DETALLE DE YAPES Y USUARIOS
		UPDATE 	TRANSACCIONES.DETALLE_USUYAPE
			SET	COD_USU = 3
		WHERE COD_USU = 1 AND COD_YAP = 1;		-- TENER ESPECIAL CUIDADO CON EL CODIGO DE USUARIO A MODIFICAR
        
/*
	MODELO PARA ELIMINAR UNA TRANSACCION (YAPE)
*/

	-- PASO 1 : CAMBIAR EL ESTADO DE LA TRANSACCION Y  ACTUALIZAR LA FECHA DEL YAPE
    UPDATE  TRANSACCIONES.YAPE
		SET EST_YAP = 'Eliminado',
			FEC_YAP = NOW()
	WHERE COD_YAP = 1;
    
    insert intO INFORMATIVOS.COMISION VALUES (20.5, NOW());
    insert intO INFORMATIVOS.COMISION VALUES (15.2, NOW());